var express = require('express');
var router = express.Router();
var passport = require('passport');
var authController = require('../app/authorization/controllers/AuthController.js');
var passportConfig = require('../app/authorization/passport.js');
var authUtil = require('../app/authorization/util/AuthUtil.js');
router.post('/signup',authController.localSignup);
router.post('/login',authController.localLogin);
router.post('/logout',authController.logout);
router.delete('/signup',authController.deleteLocalUser);
module.exports = router;
